# Generated by Django 4.1.3 on 2023-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='primeiro nome')),
                ('last_name', models.CharField(max_length=32, verbose_name='último nome')),
                ('phone', models.CharField(max_length=14, verbose_name='telefone')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
            ],
        ),
    ]
