# Generated by Django 4.1.3 on 2023-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
