# Generated by Django 4.1.3 on 2023-02-02 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sale',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='preço'),
            preserve_default=False,
        ),
    ]
