# Generated by Django 4.1.3 on 2023-01-08 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='preço')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('validity', models.DateField(verbose_name='validade')),
                ('category', models.CharField(blank=True, choices=[('Salgado', 'Salgado'), ('Doce', 'Doce'), ('Bebida', 'Bebida'), ('Especial', 'Especial'), ('Outros', 'Outros')], max_length=20, null=True, verbose_name='categoria')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='descrição')),
            ],
        ),
    ]
